[workspace]
members = ["mfkdf2", "mfkdf2-wasm", "mfkdf2-py"]

[workspace.dependencies]
mfkdf2 = { path = "mfkdf2" }

aes = { version = "0.8", default-features = false }
sharks = { version = "0.5", default-features = false }
argon2 = { version = "0.5", default-features = false }
