// Generated by uniffi-bindgen-react-native
// Export the generated bindings to the app.
export * from './generated/web/mfkdf2';

// Now import the bindings so we can:
// - intialize them
// - export them as namespaced objects as the default export.
import * as mfkdf2 from './generated/web/mfkdf2';

import initAsync from './generated/web/wasm-bindgen/index.js';

export async function uniffiInitAsync() {
  const wasmPath = new URL('./generated/web/wasm-bindgen/index_bg.wasm', import.meta.url);
  const { readFile } = await import('node:fs/promises');
  const bytes = await readFile(wasmPath);
  await initAsync({ module_or_path: bytes })

  // Initialize the generated bindings: mostly checksums, but also callbacks.
  // - the boolean flag ensures this loads exactly once, even if the JS code
  //   is reloaded (e.g. during development with metro).
  mfkdf2.default.initialize();
}

// Export the crates as individually namespaced objects.
export default {
  mfkdf2,
};

