name: Reports

on:
  workflow_run:
    workflows: ["Rust", "Bindings"]
    types: [completed]

permissions:
  contents: read
  actions: read
  pages: write
  id-token: write

concurrency:
  group: pages-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Prepare site directory
        run: mkdir -p site

      - name: Download Rust report artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: rust.yaml
          branch: main
          name: rust-test-report
          path: site/rust

      - name: Download Web (TS) report artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: bindings.yaml
          branch: main
          name: mfkdf2-web-mochawesome-report
          path: site/web

      - name: Create landing index
        env:
          COMMIT_SHA: ${{ github.event.workflow_run.head_sha }}
          REPO: ${{ github.repository }}
        run: |
          set -euo pipefail
          mkdir -p site site/rust site/web

          # Force Pages to serve raw files (no Jekyll processing)
          touch site/.nojekyll

          # ---- Normalize Rust report ----
          rust_idx="$(find site/rust -maxdepth 3 -type f \( -name 'index.html' -o -name '*mochawesome*.html' -o -name '*xunit*.html' \) | head -n1 || true)"
          if [ -n "${rust_idx:-}" ] && [ "$rust_idx" != "site/rust/index.html" ]; then
            cp "$rust_idx" site/rust/index.html
          fi

          # ---- Normalize Web/TS report ----
          web_idx="$(find site/web -maxdepth 3 -type f -name 'index.html' | head -n1 || true)"
          if [ -n "${web_idx:-}" ] && [ "$web_idx" != "site/web/index.html" ]; then
            cp "$web_idx" site/web/index.html
          fi

          # Landing page with strictly relative links and commit hash
          short_sha=$(printf "%s" "${COMMIT_SHA}" | cut -c1-8)
          cat > site/index.html <<HTML
          <!doctype html>
          <html>
            <head>
              <meta charset="utf-8" />
              <meta name="viewport" content="width=device-width, initial-scale=1" />
              <title>MFKDF2 Test Reports</title>
              <style>
                body{font-family:system-ui,-apple-system,Segoe UI,Roboto,Ubuntu,Cantarell,Noto Sans,sans-serif;padding:24px;background:#111;color:#eee}
                a{color:#8ab4f8}
              </style>
            </head>
            <body>
              <h1>MFKDF2 Test Reports</h1>
              <p>Commit: <a href="https://github.com/${REPO}/commit/${COMMIT_SHA}">${short_sha}</a></p>
              <ul>
                <li><a href="./rust/index.html">Rust report</a></li>
                <li><a href="./web/index.html">Web (TS) report</a></li>
              </ul>
            </body>
          </html>
          HTML

          # Basic sanity checks to fail fast instead of deploying broken links
          test -f site/index.html
          test -f site/rust/index.html || { echo "Rust report index missing"; exit 1; }
          test -f site/web/index.html  || { echo "Web report index missing"; exit 1; }

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: test-reports
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
